### ISSUE TITLE
Failed to create RegisterType resources

### ISSUE THREAD

**Issue by ruiyaoOps** [aws-quickstart/quickstart-amazon-eks#397]
we failed to create an EKS cluster through [amazon-eks-entrypoint-new-vpc](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-entrypoint-new-vpc.template.yaml) in CloudFormation of AWS.
After investigation, we found that it was because RegisterEksClusterType RegisterHelmType RegisterKubeApplyType and RegisterKubeGetType in [amazon-eks-per-region-resources](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-per-region-resources.template.yaml) failed to create.
we got the following information from the CloudWatch:
```shell
[ERROR] DistributionNotFound: The 'semantic_version' distribution was not found and is required by the application
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 6, in <module>
    from semantic_version import Version
  File "/var/task/semantic_version/__init__.py", line 18, in <module>
    __version__ = pkg_resources.get_distribution("semantic_version").version
  File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
```

![image](https://user-images.githubusercontent.com/35256376/157008570-2f2ec720-afd3-45e9-a1ed-bbb1662c8cbc.png)

**Comment by ruiyaoOps** [comment]
parameters used
Basic configuration
AvailabilityZones: us-east-2a, us-east-2ab, us-east-2c
RemoteAccessCIDR: 0.0.0.0/0
KeyPairName: XXX
PerAccountSharedResources: AutoDetect
PerRegionSharedResources: AutoDetect

Amazon EC2 configuration
ProvisionBastionHost: Enabled

Other configurations use the default configuration

**Comment by egfanboy** [comment]
We faced the same issue. We noticed that the `semantic_version` package in python had a recent release and therefore as a workaround we pinned the version of `semantic_version` in `requirements.txt` to 2.8.5 (the previous release) and rebuild the lambda's using that which solved the issue for us.


Probably not the ideal solution but a potential workaround.

**Comment by disparo13** [comment]
@egfanboy thanks for the workaround! To others - you need to re-create zips for `registerCustomResource` and `registerType` Lambdas. First - make a local copy of `aws-quickstart`bucket, then rebuild needed zips in `functions/packages` directory using sources from [https://github.com/aws-quickstart/quickstart-amazon-eks/tree/main/functions/source](here).

**Comment by moophlo** [comment]
@egfanboy can you explain better how to pin version in requirements.txt? I'm experiencing the same issue.
If I look here https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/functions/source/registerType/requirements.txt inside the file I do have only "semantic_version" but no explicit version. Should I change "semantic_version" to "2.8.5" ?

**Comment by moophlo** [comment]
ok I put "semantic_version==2.8.5" in requirements.txt and then I've builded with "bash -x ./lambda_package.sh registerType".
Now I do have the correct lambda.zip  for registerType. How can I use the custom one instead the one built during the execution of this template? https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-entrypoint-new-vpc.template.yaml

**Comment by troy-ameigh** [comment]
We have just pushed a fix that locks the version for the semantic version module. Thank you all for the input.

**Comment by awsari** [comment]
#399 is related

**Comment by troy-ameigh** [comment]
sorry for the late reply. packages are pushed to S3

**Comment by troy-ameigh** [comment]
There is a new update in S3 as of tonight. Issue should be resolved.

**Comment by troy-ameigh** [comment]
Updates are in the S3 buckets, and semantic version issue should be resolved.

**Comment by ArayaMartiin** [comment]
Hola, volvi a correr a ymel para crear el cluster y ahora me arroja el siguiente error:

ID: eks-quickstart-AccountSharedResources

**The following resource(s) failed to create: [CleanupLambdasRole, RegisterTypeRole, CleanupSecurityGroupDependenciesRole, ResourceReaderRole, CloudformationVPCRoleCreationRole, ControlPlaneRole, ManagedNodeInstanceRole, CopyZipsRole, GetCallerArnRole, NodeSGRole, DeleteBucketContentsRole, CreateVpcRoleRole, FargateProfileRole, CleanupLoadBalancersRole, UnmanagedNodeInstanceRole, ParameterResolverRole, RegisterCustomResourceRole, FargateExecutionRole]. Delete requested by user.**

**Comment by troy-ameigh** [comment]
resolved

**Comment by Ganesh-Yeole** [comment]
We are still getting 'semantic_version' issue when launching from aws-quickstart bucket.
