### ISSUE TITLE
Failed to create new EKS when using EKS QS as submodule

### ISSUE THREAD

**Issue by git4rk** [aws-quickstart/quickstart-amazon-eks#408]
I need some help figuring out how to use **nested** submodules. 

**Background information:**
- I am creating a CF template to setup new EKS on new VPC and install an application in EKS.
- First thing I am trying is to import EKS QS as a submodule in my repo and use it in my template, following the steps in [Quick Start workshop doc](https://workshop.quickstart.awspartner.com/60_implementing/10_adding_submodules.html)
- So, my repo has these files
    - /template/my-template.yaml
    - /submodules/quickstart-amazon-eks (this contains [all EKS files](https://github.com/aws-quickstart/quickstart-amazon-eks), except [submodules within EKS repo](https://github.com/aws-quickstart/quickstart-amazon-eks/tree/main/submodules))
- I use testcat to load the template to S3 bucket and run it. 
- My template fails to create EKS with obscure error (`S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html`) and I think I am running into issues related to nested submodules.

**My investigation:**
- My CF template calls 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-amazon-eks/templates/amazon-eks-entrypoint-new-vpc.template.yaml', and
- `amazon-eks-entrypoint-new-vpc.template.yaml` calls 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/amazon-eks-advanced-configuration.template.yaml'
- So, the path, `templates/amazon-eks-advanced-configuration.template.yaml` is not correct since for my S3 bucket it should be `submodules/quickstart-amazon-eks/templates/amazon-eks-advanced-configuration.template.yaml` 
- All the templates called from amazon-eks-entrypoint-new-vpc.template.yaml have the similar paths, which is not correct when EKS is used as submodule.

**Questions:**
1. Shouldn't EKS QS be using relative path for the URLs, so that it can be used as submodule?
2. EKS QS has its own submodules (example quickstart-aws-vpc/), so even if item 1 is fixed, my repo will not have EKS' submodules and it will fail again when `submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml` will be called. 

How can I resolve this issue?

**Comment by troy-ameigh** [comment]
Do the following and try again.

git submodule update --init --recursive

**Comment by troy-ameigh** [comment]
Updates are in the S3 buckets, and semantic version issue should be resolved.

**Comment by git4rk** [comment]
@troy-ameigh Thanks for the suggestion. `git submodule update --init --recursive` copies the files recursively. But my deploy still fails due to nested submodules.

Here are more details to clarify the issue. Please pay attention to the path.

Directory/S3 bucket structure (after `git submodule update --init --recursive`):
- templates/myTemplate.yaml
- submodules/
    - quickstart-amazon-eks/
        - templates/amazon-eks-entrypoint-new-vpc.template.yaml
        - submodules/
            - quickstart-aws-vpc/
                - templates/aws-vpc.template.yaml

1. My CF template is at 'BUCKET_URL/templates/myTemplate.yaml': **This is found**
2. This calls 'BUCKET_URL/submodules/quickstart-amazon-eks/templates/amazon-eks-entrypoint-new-vpc.template.yaml': **This is found**
3. `amazon-eks-entrypoint-new-vpc.template.yaml` calls `BUCKET_URL/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml: **NOT FOUND**
4. This path is wrong, since `quickstart-aws-vpc/` is a submodule of `quickstart-amazon-eks` and is found under 'BUCKET_URL/submodules/quickstart-amazon-eks/submodules', not under `BUCKET_URL/submodules/'.
5. There are several such submodules used by `quickstart-amazon-eks`. But since `quickstart-amazon-eks` uses [absolute path](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/a19f1ec244858a5e65672dd04b22624767f9f3ee/templates/amazon-eks-entrypoint-new-vpc.template.yaml#L729) it is looking for all submodules to be at the 'BUCKET_URL' level, not two levels down.

Hope this helps understand the issue. If the `TemplateURL` can be set as relative path then that should resolve the issue.

Thanks

**Comment by troy-ameigh** [comment]
Ranjan,

Thanks for the information, are you will to share your template so I can understand how you are pulling in the EKS submodule, as you should not need to pull in the vpc separately.

This is the path that the EKS QS looks for the VPC submodule. Which gets populated at time of launch.

- 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml'


--

Troy Ameigh
Sr. Partner Solutions Architect
Amazon Web Services
M: (512)201-0430
Email: ***@***.******@***.***>

[signature_1644085449]

[signature_1551535262]<https://www.youracclaim.com/badges/9441f5cd-c21b-4c41-829b-07906ccc7bcc/public_url>[signature_1322984921]<https://www.youracclaim.com/badges/6e89fb3b-8b3b-40ed-9558-50129de22714/public_url>[signature_1616915995]<https://www.youracclaim.com/badges/f1f7a8cb-5f0d-4de7-b286-4dbecdba9c98/public_url>[signature_707246526]<https://www.youracclaim.com/badges/aad71e34-b480-47f3-a315-34693d668bdb/public_url>[signature_1128524595]<https://www.youracclaim.com/badges/90e436f3-b80c-4a5d-aa7d-fd4b3045ef4e/public_url>

Thoughts on our interaction? Provide feedback here<https://feedback.aws.amazon.com/?ea=ameighta&fn=Troy&ln=Ameigh>.


From: Ranjan Kumar ***@***.***>
Reply-To: aws-quickstart/quickstart-amazon-eks ***@***.***>
Date: Monday, April 4, 2022 at 1:38 PM
To: aws-quickstart/quickstart-amazon-eks ***@***.***>
Cc: "Ameigh, Troy" ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-quickstart/quickstart-amazon-eks] Failed to create new EKS when using EKS QS as submodule (Issue #408)


@troy-ameigh<https://github.com/troy-ameigh> Thanks for the suggestion. git submodule update --init --recursive copies the files recursively. But my deploy still fails due to nested submodules.

Here are more details to clarify the issue. Please pay attention to the path.

Directory/S3 bucket structure (after git submodule update --init --recursive):
·         templates/myTemplate.yaml
·         submodules/
o    quickstart-amazon-eks/
§  templates/amazon-eks-entrypoint-new-vpc.template.yaml
§  submodules/
§  quickstart-aws-vpc/
§  templates/aws-vpc.template.yaml
1.       My CF template is at 'BUCKET_URL/templates/myTemplate.yaml': This is found
2.       This calls 'BUCKET_URL/submodules/quickstart-amazon-eks/templates/amazon-eks-entrypoint-new-vpc.template.yaml': This is found
3.       amazon-eks-entrypoint-new-vpc.template.yaml calls `BUCKET_URL/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml: NOT FOUND
4.       This path is wrong, since quickstart-aws-vpc/ is a submodule of quickstart-amazon-eks and is found under 'BUCKET_URL/submodules/quickstart-amazon-eks/submodules', not under `BUCKET_URL/submodules/'.
5.       There are several such submodules used by quickstart-amazon-eks. But since quickstart-amazon-eks uses absolute path<https://github.com/aws-quickstart/quickstart-amazon-eks/blob/a19f1ec244858a5e65672dd04b22624767f9f3ee/templates/amazon-eks-entrypoint-new-vpc.template.yaml#L729> it is looking for all submodules to be at the 'BUCKET_URL' level, not two levels down.

Hope this helps understand the issue. If the TemplateURL can be set as relative path then that should resolve the issue.

Thanks

**Comment by git4rk** [comment]
@troy-ameigh Here is what I have:
```
Resources:
  NewEKSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-amazon-eks/templates/amazon-eks-entrypoint-new-vpc.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
       . . . 
```

Like I mentioned earlier, `submodules/quickstart-amazon-eks/templates/amazon-eks-entrypoint-new-vpc.template.yaml` is found in the bucket but the downstream yamls are not.

**Comment by git4rk** [comment]
If there is a way to use relative path for `TemplateURL` then that should resolve the issue.

**Comment by troy-ameigh** [comment]
Ranjan,

The Quick Starts are designed this way as they are meant to launch from our S3 buckets. So if use relative path it will break the flexibility to deploy by other means. The issue appears to be how the submodules are getting pulled in for you. I am not able to duplicate the issue, so can we try this.  To confirm are you launching this from our S3 bucket or have you cloned the repo then copied it to an S3 bucket you own.


--

Troy Ameigh
Sr. Partner Solutions Architect
Amazon Web Services
M: (512)201-0430
Email: ***@***.******@***.***>

[signature_409352993]

[signature_975020284]<https://www.youracclaim.com/badges/9441f5cd-c21b-4c41-829b-07906ccc7bcc/public_url>[signature_747070238]<https://www.youracclaim.com/badges/6e89fb3b-8b3b-40ed-9558-50129de22714/public_url>[signature_276118993]<https://www.youracclaim.com/badges/f1f7a8cb-5f0d-4de7-b286-4dbecdba9c98/public_url>[signature_1969481054]<https://www.youracclaim.com/badges/aad71e34-b480-47f3-a315-34693d668bdb/public_url>[signature_1781579448]<https://www.youracclaim.com/badges/90e436f3-b80c-4a5d-aa7d-fd4b3045ef4e/public_url>

Thoughts on our interaction? Provide feedback here<https://feedback.aws.amazon.com/?ea=ameighta&fn=Troy&ln=Ameigh>.


From: Ranjan Kumar ***@***.***>
Reply-To: aws-quickstart/quickstart-amazon-eks ***@***.***>
Date: Monday, April 4, 2022 at 4:14 PM
To: aws-quickstart/quickstart-amazon-eks ***@***.***>
Cc: "Ameigh, Troy" ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-quickstart/quickstart-amazon-eks] Failed to create new EKS when using EKS QS as submodule (Issue #408)


If there is a way to use relative path for TemplateURL then that should resolve the issue.

**Comment by git4rk** [comment]
@troy-ameigh I guess, if I launch it from your S3 bucket then I do not need to add EKS as submodule in my repo. Can you please share the S3 URL I should be using for your bucket?

**Comment by troy-ameigh** [comment]
@git4rk What are you trying to accomplish

**Comment by git4rk** [comment]
@troy-ameigh I am trying to create a CF template which will create new EKS on new VPC (using submodule), then install a Kubernetes Operator and an application. If you could point me to some code/repo which uses EKS as submodule, that will be great.

Thanks

**Comment by git4rk** [comment]
@troy-ameigh I tried to use direct EKS QS URL (https://s3.amazonaws.com/aws-quickstart/quickstart-amazon-eks/templates/amazon-eks-entrypoint-new-vpc.template.yaml) in my template but that did not work since EKS templates still use parameterized URL ('https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/amazon-eks-prerequisites.template.yaml'), which get resolved to my bucket, where these yamls do not exist.

What does your S3 bucket structure look like when you use EKS as submodule and what do you set your TemplateURL to be (to create new EKS in a new VPC)?

Thank you very much for your patience with helping me with this issue.

**Comment by troy-ameigh** [comment]
@git4rk Look at the following it uses EKS as a submodule. 

https://github.com/aws-quickstart/quickstart-qingcloud-kubesphere

I think I understand your issue better. Add the VPC as a submodule, of its own like in Kubesphere, it will make your life easier. Once you get so far done with nested stacks it can be hard to properly call them.

**Comment by troy-ameigh** [comment]
@git4rk is there any update on this?

**Comment by git4rk** [comment]
@troy-ameigh I have not tried it since I was told using EKS QS (as submodule) is not recommended and I need to use https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html.
